name: Build

on:
  push:
    tags-ignore:
      - "v*"
    branches:
      - "**"
  pull_request:
  schedule:
    - cron: '0 0 * * SUN'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: smallstep/workflows/.github/workflows/goLint.yml@main

  test:
    needs: lint
    uses: smallstep/workflows/.github/workflows/goTest.yml@main
